<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UTB.Rusryl_Interaktivni_mapa_kasina.Application\UTB.Rusryl_Interaktivni_mapa_kasina.Application.csproj" />
    <ProjectReference Include="..\UTB.Rusryl_Interaktivni_mapa_kasina.Domain\UTB.Rusryl_Interaktivni_mapa_kasina.Domain.csproj" />
    <ProjectReference Include="..\UTB.Rusryl_Interaktivni_mapa_kasina.Infrastructure\UTB.Rusryl_Interaktivni_mapa_kasina.Infrastructure.csproj" />
  </ItemGroup>

</Project>
